# Generated by Django 3.2.8 on 2021-10-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_name', models.CharField(max_length=50)),
                ('gc_sam', models.CharField(max_length=50)),
                ('gc_pic', models.ImageField(upload_to='categorary')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gi_name', models.CharField(max_length=50)),
                ('gi_price', models.IntegerField(default=0)),
                ('gi_des', models.CharField(max_length=3000)),
                ('gi_pic', models.ImageField(upload_to='goods')),
                ('gi_cag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodscategory')),
            ],
        ),
    ]
