# Generated by Django 3.2.8 on 2021-10-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscategory',
            name='gc_sam',
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='gc_pic',
            field=models.ImageField(upload_to='category'),
        ),
    ]
