# Generated by Django 3.2.8 on 2021-10-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20211020_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='gc_pic',
            field=models.ImageField(upload_to='cag'),
        ),
    ]
